name: dotnet package

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.x' ]
        target: [ 'win-x64', 'win-arm64' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build ${{ matrix.target }}
        run: dotnet publish -r ${{ matrix.target }}
      - name: Run tests
        run: dotnet test
